import './redispatch-cases.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import pg from 'pg';
import {generateOffers} from '../src/dispatch.js';
import {sweepAndRedispatch} from '../src/redispatch.js';
import {acceptOffer} from '../src/engine.js';
import {transitionBooking,TransitionRejected} from '../src/lifecycle.js';
const url=process.env.TEST_DATABASE_URL;
test('Postgres booking, dispatch, acceptance and conflict', {skip:!url?'TEST_DATABASE_URL required':false}, async()=>{
 if(!new URL(url!).pathname.endsWith('/homiq_test')) throw new Error('Refusing destructive integration setup outside homiq_test');
 const pool=new pg.Pool({connectionString:url});
 try {
  await pool.query('BEGIN'); await pool.query('ROLLBACK');
  await pool.query('DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public');
  await pool.query(readFileSync('sql/001_init.sql','utf8'));
  await pool.query(readFileSync('sql/002_seed_demo.sql','utf8'));
  const customer='10000000-0000-4000-8000-000000000001';
  const starts=new Date(Date.now()+3*86400000), ends=new Date(starts.getTime()+2*3600000);
  const booking=await pool.query("INSERT INTO bookings(customer_id,category_code,starts_at,ends_at,address_text,intake) VALUES($1,'repairs',$2,$3,'Calamba City', $4) RETURNING id",[customer,starts,ends,JSON.stringify({problemType:'leak',description:'Sink leak'})]);
  const id=booking.rows[0].id;
  const offers=await generateOffers(pool,id);assert.ok(offers.offersCreated>0);
  const rows=await pool.query('SELECT o.id,p.user_id FROM dispatch_offers o JOIN providers p ON p.id=o.provider_id WHERE booking_id=$1',[id]);
  const attempts=await Promise.allSettled(rows.rows.slice(0,2).map(o=>acceptOffer(pool,o.id,o.user_id)));
  assert.equal(attempts.filter(x=>x.status==='fulfilled').length,1);
  const assignment=await pool.query('SELECT * FROM assignments WHERE booking_id=$1',[id]);assert.equal(assignment.rowCount,1);
  const status=await pool.query('SELECT status FROM bookings WHERE id=$1',[id]);assert.equal(status.rows[0].status,'confirmed');
  const provider=attempts.find(x=>x.status==='fulfilled') as PromiseFulfilledResult<{bookingId:string;providerId:string;status:string}>;
  const providerUser=await pool.query('SELECT user_id FROM providers WHERE id=$1',[provider.value.providerId]);
  const providerId=providerUser.rows[0].user_id;
  await assert.rejects(transitionBooking(pool,id,customer,'start'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);
  assert.equal((await transitionBooking(pool,id,providerId,'start')).status,'in_progress');
  await assert.rejects(transitionBooking(pool,id,providerId,'start'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);
  assert.equal((await transitionBooking(pool,id,providerId,'complete')).status,'completed');
  assert.equal((await transitionBooking(pool,id,customer,'dispute')).status,'disputed');
  await assert.rejects(transitionBooking(pool,id,customer,'cancel'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);
  const sweep=await sweepAndRedispatch(pool);
  assert.ok(sweep.bookingsChecked>=0);
  const history=await pool.query('SELECT event_type FROM booking_events WHERE booking_id=$1 ORDER BY id',[id]);
  assert.deepEqual(history.rows.slice(-3).map(x=>x.event_type),['start','complete','dispute']);
  const cancellation=await pool.query("INSERT INTO bookings(customer_id,category_code,starts_at,ends_at,address_text,intake) VALUES($1,'repairs',$2,$3,'Calamba City','{}') RETURNING id",[customer,starts,ends]);
  const cancelId=cancellation.rows[0].id;
  await generateOffers(pool,cancelId);
  assert.equal((await transitionBooking(pool,cancelId,customer,'cancel')).status,'canceled');
  const pending=await pool.query("SELECT count(*)::int AS n FROM dispatch_offers WHERE booking_id=$1 AND status='pending'",[cancelId]);
  assert.equal(pending.rows[0].n,0);
  await assert.rejects(transitionBooking(pool,cancelId,customer,'cancel'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);

 } finally {await pool.end();}
});
