import './redispatch-cases.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import pg from 'pg';
import express from 'express';
import {walletRoutes} from '../src/wallet-routes.js';
import {cashoutRoutes} from '../src/cashout-routes.js';
import {generateOffers} from '../src/dispatch.js';
import {sweepAndRedispatch} from '../src/redispatch.js';
import {acceptOffer} from '../src/engine.js';
import {transitionBooking,TransitionRejected} from '../src/lifecycle.js';
const url=process.env.TEST_DATABASE_URL;
test('Postgres booking, dispatch, acceptance and conflict', {skip:!url?'TEST_DATABASE_URL required':false}, async()=>{
 if(!new URL(url!).pathname.endsWith('/homiq_test')) throw new Error('Refusing destructive integration setup outside homiq_test');
 const pool=new pg.Pool({connectionString:url});
 try {
  await pool.query('BEGIN'); await pool.query('ROLLBACK');
  await pool.query('DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public');
  await pool.query(readFileSync('sql/001_init.sql','utf8'));
  await pool.query(readFileSync('sql/002_seed_demo.sql','utf8'));
  await pool.query(readFileSync('sql/003_demo_wallet.sql','utf8'));
  await pool.query(readFileSync('sql/004_demo_cashout.sql','utf8'));
  process.env.ALLOW_INSECURE_DEV_AUTH='true';process.env.ENABLE_DEMO_ROUTES='true';process.env.DEV_ADMIN_KEY='cashout-test-admin';
  const customer='10000000-0000-4000-8000-000000000001';
  const starts=new Date(Date.now()+3*86400000), ends=new Date(starts.getTime()+2*3600000);
  const booking=await pool.query("INSERT INTO bookings(customer_id,category_code,starts_at,ends_at,address_text,intake) VALUES($1,'repairs',$2,$3,'Calamba City', $4) RETURNING id",[customer,starts,ends,JSON.stringify({problemType:'leak',description:'Sink leak'})]);
  const id=booking.rows[0].id;
  const offers=await generateOffers(pool,id);assert.ok(offers.offersCreated>0);
  const rows=await pool.query('SELECT o.id,p.user_id FROM dispatch_offers o JOIN providers p ON p.id=o.provider_id WHERE booking_id=$1',[id]);
  const attempts=await Promise.allSettled(rows.rows.slice(0,2).map(o=>acceptOffer(pool,o.id,o.user_id)));
  assert.equal(attempts.filter(x=>x.status==='fulfilled').length,1);
  const assignment=await pool.query('SELECT * FROM assignments WHERE booking_id=$1',[id]);assert.equal(assignment.rowCount,1);
  const status=await pool.query('SELECT status FROM bookings WHERE id=$1',[id]);assert.equal(status.rows[0].status,'confirmed');
  const provider=attempts.find(x=>x.status==='fulfilled') as PromiseFulfilledResult<{bookingId:string;providerId:string;status:string}>;
  const providerUser=await pool.query('SELECT user_id FROM providers WHERE id=$1',[provider.value.providerId]);
  const providerId=providerUser.rows[0].user_id;
  await assert.rejects(transitionBooking(pool,id,customer,'start'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);
  await assert.rejects(transitionBooking(pool,id,providerId,'start'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);
  await pool.query("INSERT INTO demo_wallet_holds(booking_id,customer_id,amount_cents,status) VALUES($1,$2,50000,'reserved')",[id,customer]);
  await pool.query('UPDATE demo_wallets SET reserved_cents=reserved_cents+50000 WHERE user_id=$1',[customer]);
  assert.equal((await transitionBooking(pool,id,providerId,'start')).status,'in_progress');
  await assert.rejects(transitionBooking(pool,id,providerId,'start'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);
  assert.equal((await transitionBooking(pool,id,providerId,'complete')).status,'completed');
  assert.equal((await transitionBooking(pool,id,customer,'dispute')).status,'disputed');
  await assert.rejects(transitionBooking(pool,id,customer,'cancel'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);
  const sweep=await sweepAndRedispatch(pool);
  assert.ok(sweep.bookingsChecked>=0);
  const history=await pool.query('SELECT event_type FROM booking_events WHERE booking_id=$1 ORDER BY id',[id]);
  assert.deepEqual(history.rows.slice(-3).map(x=>x.event_type),['start','complete','dispute']);
  const app=express();app.use(express.json());walletRoutes(app,pool);cashoutRoutes(app,pool);
  const server=await new Promise<import('node:http').Server>(resolve=>{const instance=app.listen(0,'127.0.0.1',()=>resolve(instance))});
  try{
   const address=server.address();if(!address||typeof address==='string')throw new Error('No test server');
   const root='http://127.0.0.1:'+address.port;
   const post=async(path:string,actor:string,body?:unknown)=>{
    const response=await fetch(root+path,{method:'POST',headers:{'Content-Type':'application/json','x-dev-user-id':actor},body:JSON.stringify(body||{})});
    return {status:response.status,body:await response.json()};
   };
   const second=await pool.query("INSERT INTO bookings(customer_id,category_code,starts_at,ends_at,address_text,intake,status) VALUES($1,'repairs',$2,$3,'Calamba City','{}','confirmed') RETURNING id",[customer,starts,ends]);
   const quoteBooking=second.rows[0].id;
   await pool.query('INSERT INTO assignments(booking_id,provider_id) VALUES($1,$2)',[quoteBooking,provider.value.providerId]);
   const quoted=await post('/api/bookings/'+quoteBooking+'/quotes',providerId,{amountCents:125000});
   assert.equal(quoted.status,201);
   const rejectedActor=await post('/api/bookings/'+quoteBooking+'/quotes/'+quoted.body.id+'/decision',providerId,{decision:'approve'});
   assert.equal(rejectedActor.status,403);
   const underfunded=await pool.query("INSERT INTO bookings(customer_id,category_code,starts_at,ends_at,address_text,intake,status) VALUES($1,'repairs',$2,$3,'Calamba City','{}','confirmed') RETURNING id",[customer,starts,ends]);
   await pool.query('INSERT INTO assignments(booking_id,provider_id) VALUES($1,$2)',[underfunded.rows[0].id,provider.value.providerId]);
   const largeQuote=await post('/api/bookings/'+underfunded.rows[0].id+'/quotes',providerId,{amountCents:600000});
   assert.equal(largeQuote.status,201);
   const denied=await post('/api/bookings/'+underfunded.rows[0].id+'/quotes/'+largeQuote.body.id+'/decision',customer,{decision:'approve'});
   assert.equal(denied.status,409);
   const approved=await post('/api/bookings/'+quoteBooking+'/quotes/'+quoted.body.id+'/decision',customer,{decision:'approve'});
   assert.equal(approved.status,200);
   const repeated=await post('/api/bookings/'+quoteBooking+'/quotes/'+quoted.body.id+'/decision',customer,{decision:'approve'});
   assert.equal(repeated.status,409);
   const held=await pool.query('SELECT amount_cents,status FROM demo_wallet_holds WHERE booking_id=$1',[quoteBooking]);
   assert.equal(held.rows[0].status,'reserved');
   assert.equal(Number(held.rows[0].amount_cents),125000);
   const premature=await post('/api/bookings/'+quoteBooking+'/confirm-delivery',customer);
   assert.equal(premature.status,409);
   assert.equal((await transitionBooking(pool,quoteBooking,providerId,'start')).status,'in_progress');
   assert.equal((await transitionBooking(pool,quoteBooking,providerId,'complete')).status,'completed');
   const [settle1,settle2]=await Promise.all([post('/api/bookings/'+quoteBooking+'/confirm-delivery',customer),post('/api/bookings/'+quoteBooking+'/confirm-delivery',customer)]);
   assert.equal(settle1.status,200);assert.equal(settle2.status,200);
   assert.equal((await pool.query("SELECT COUNT(*)::int AS n FROM demo_wallet_ledger WHERE booking_id=$1 AND entry_type='capture'",[quoteBooking])).rows[0].n,1);
   assert.equal((await pool.query('SELECT status FROM bookings WHERE id=$1',[quoteBooking])).rows[0].status,'settled');
   const cashout=(amountCents:number)=>post('/api/provider/cashouts',providerId,{amountCents,method:'gcash',destinationLabel:'Test wallet'});
   const unauthorized=await post('/api/provider/cashouts',customer,{amountCents:10000,method:'gcash',destinationLabel:'Test wallet'});
   assert.equal(unauthorized.status,403);
   const tooMuch=await cashout(200000);assert.equal(tooMuch.status,409);
   const [first,secondCashout]=await Promise.all([cashout(80000),cashout(80000)]);
   assert.equal([first.status,secondCashout.status].filter(x=>x===201).length,1);
   const request=[first,secondCashout].find(x=>x.status===201)!.body;
   const adminPost=async(decision:'approve'|'reject',id:string)=>{const response=await fetch(root+'/api/dev/admin/cashouts/'+id+'/decision',{method:'POST',headers:{'Content-Type':'application/json','x-dev-admin-key':'cashout-test-admin'},body:JSON.stringify({decision})});return {status:response.status,body:await response.json()}};
   const [decision1,decision2]=await Promise.all([adminPost('approve',request.id),adminPost('approve',request.id)]);
   assert.deepEqual([decision1.status,decision2.status].sort(),[200,409]);
   const providerWallet=await pool.query('SELECT balance_cents,reserved_cents FROM demo_wallets WHERE user_id=$1',[providerId]);
   assert.equal(Number(providerWallet.rows[0].balance_cents),45000);
   assert.equal(Number(providerWallet.rows[0].reserved_cents),0);
   const refundRequest=await cashout(25000);assert.equal(refundRequest.status,201);
   const rejected=await adminPost('reject',refundRequest.body.id);assert.equal(rejected.status,200);
   const afterReject=await pool.query('SELECT balance_cents,reserved_cents FROM demo_wallets WHERE user_id=$1',[providerId]);
   assert.equal(Number(afterReject.rows[0].balance_cents),45000);
   assert.equal(Number(afterReject.rows[0].reserved_cents),0);

  }finally{await new Promise<void>((resolve,reject)=>server.close(err=>err?reject(err):resolve()))}
  const cancellation=await pool.query("INSERT INTO bookings(customer_id,category_code,starts_at,ends_at,address_text,intake) VALUES($1,'repairs',$2,$3,'Calamba City','{}') RETURNING id",[customer,starts,ends]);
  const cancelId=cancellation.rows[0].id;
  await generateOffers(pool,cancelId);
  await pool.query("UPDATE bookings SET status='confirmed' WHERE id=$1",[cancelId]);
  await pool.query("INSERT INTO demo_wallet_holds(booking_id,customer_id,amount_cents,status) VALUES($1,$2,25000,'reserved')",[cancelId,customer]);
  await pool.query('UPDATE demo_wallets SET reserved_cents=reserved_cents+25000 WHERE user_id=$1',[customer]);
  assert.equal((await transitionBooking(pool,cancelId,customer,'cancel')).status,'canceled');
  const released=await pool.query('SELECT status FROM demo_wallet_holds WHERE booking_id=$1',[cancelId]);
  assert.equal(released.rows[0].status,'released');
  const pending=await pool.query("SELECT count(*)::int AS n FROM dispatch_offers WHERE booking_id=$1 AND status='pending'",[cancelId]);
  assert.equal(pending.rows[0].n,0);
  await assert.rejects(transitionBooking(pool,cancelId,customer,'cancel'),(e:unknown)=>e instanceof TransitionRejected&&e.code===409);

 } finally {await pool.end();}
});
