import {BrandAsset,CategoryAsset} from './VisualAssets';
import {demoPricing,php} from './pricing';
import {useEffect,useState} from 'react';
import {Home,CalendarDays,UserRound,ShieldCheck,ArrowLeft,ArrowRight,Search,MapPin,Clock3,CheckCircle2,AlertCircle,BriefcaseBusiness} from 'lucide-react';
type Category='repairs'|'cleaning'|'maintenance'|'outdoor'|'moving_delivery'|'personal_assistance';
type Account={id:string;display_name:string};
type Booking={id:string;category_code:Category;status:string;starts_at:string;address_text:string};
const catalog:{id:Category;name:string;icon:string;description:string;fields:{key:string;label:string;placeholder:string}[]}[]=[
{id:'repairs',name:'Repairs',icon:'🔧',description:'Plumbing, electrical, appliance repair',fields:[{key:'problemType',label:'Problem type',placeholder:'e.g. Leaking faucet'},{key:'description',label:'Describe the problem',placeholder:'What needs fixing?'}]},
{id:'cleaning',name:'Cleaning',icon:'🧼',description:'Housekeeping, deep cleaning, laundry',fields:[{key:'propertyType',label:'Property type',placeholder:'House, condo, studio'},{key:'cleaningLevel',label:'Cleaning level',placeholder:'Regular, deep, move-out'},{key:'suppliesProvidedBy',label:'Supplies provided by',placeholder:'Customer or professional'}]},
{id:'maintenance',name:'Maintenance',icon:'🛠️',description:'Carpentry, painting, aircon servicing',fields:[{key:'workType',label:'Work type',placeholder:'e.g. Aircon servicing'},{key:'description',label:'Job description',placeholder:'Describe the work'}]},
{id:'outdoor',name:'Outdoor',icon:'🌿',description:'Gardening, landscaping, pest control',fields:[{key:'serviceType',label:'Service type',placeholder:'e.g. Lawn trimming'},{key:'propertyType',label:'Property type',placeholder:'e.g. Residential yard'}]},
{id:'moving_delivery',name:'Moving & Delivery',icon:'📦',description:'Furniture moving, hauling, errands',fields:[{key:'itemDescription',label:'Items to move',placeholder:'List the items'},{key:'pickupAddress',label:'Pickup address',placeholder:'Pickup location'},{key:'dropoffAddress',label:'Drop-off address',placeholder:'Destination'}]},
{id:'personal_assistance',name:'Personal Assistance',icon:'🤝',description:'Home assistance, caregiving, pet care',fields:[{key:'assistanceType',label:'Assistance type',placeholder:'e.g. Pet care'},{key:'description',label:'Service requirements',placeholder:'Describe the assistance'}]}
];
const API='/api';
async function request<T>(url:string,options?:RequestInit):Promise<T>{const res=await fetch(API+url,options);const data=await res.json();if(!res.ok)throw new Error(typeof data.error==='string'?data.error:'Request failed');return data as T;}
export default function App(){
const [screen,setScreen]=useState<'home'|'book'|'history'|'account'>('home');
const [category,setCategory]=useState(catalog[1]);
const [accounts,setAccounts]=useState<Account[]>([]);
const [account,setAccount]=useState(()=>localStorage.getItem('homiq:customer')||'');
const [ratings,setRatings]=useState<Record<string,number>>(()=>{try{return JSON.parse(localStorage.getItem('homiq:ratings')||'{}')}catch{return {}}});
const [bookings,setBookings]=useState<Booking[]>([]);
const [form,setForm]=useState<Record<string,string>>({});
const [date,setDate]=useState('');const [address,setAddress]=useState('');
const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [search,setSearch]=useState('');
const [apiReady,setApiReady]=useState(false);
const [selected,setSelected]=useState<string|null>(null);
const [events,setEvents]=useState<{event_type:string;created_at:string;detail:Record<string,unknown>}[]>([]);
const [detailBusy,setDetailBusy]=useState(false);
useEffect(()=>{request<Account[]>('/dev/customers').then(a=>{setAccounts(a);setAccount(previous=>a.some(x=>x.id===previous)?previous:a[0]?.id||'');setApiReady(true)}).catch(()=>{setError('Development API is unavailable. Start the backend and seed the database.');setApiReady(false)})},[]);
useEffect(()=>{if(account)localStorage.setItem('homiq:customer',account)},[account]);
useEffect(()=>{localStorage.setItem('homiq:ratings',JSON.stringify(ratings))},[ratings]);
useEffect(()=>{if(!account)return;setSelected(null);setEvents([]);setBookings([]);request<Booking[]>('/dev/bookings',{headers:{'x-dev-user-id':account}}).then(setBookings).catch(e=>setError(e.message))},[account]);
async function viewBooking(id:string){setSelected(id);setEvents([]);setDetailBusy(true);setError('');try{setEvents(await request<{event_type:string;created_at:string;detail:Record<string,unknown>}[]>('/bookings/'+id+'/events',{headers:{'x-dev-user-id':account}}))}catch(e){setError((e as Error).message)}finally{setDetailBusy(false)}}
async function disputeBooking(id:string){if(!account)return;setBusy(true);setError('');try{const r=await fetch('/api/bookings/'+id+'/transition',{method:'POST',headers:{'Content-Type':'application/json','x-dev-user-id':account},body:JSON.stringify({action:'dispute'})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Dispute failed');setBookings(await request<Booking[]>('/dev/bookings',{headers:{'x-dev-user-id':account}}));await viewBooking(id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function choose(id:Category){setCategory(catalog.find(x=>x.id===id)!);setForm({});setError('');setScreen('book')}
async function cancelBooking(id:string){if(!account)return;setBusy(true);setError('');try{const r=await fetch('/api/bookings/'+id+'/transition',{method:'POST',headers:{'Content-Type':'application/json','x-dev-user-id':account},body:JSON.stringify({action:'cancel'})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Cancellation failed');setBookings(await request<Booking[]>('/dev/bookings',{headers:{'x-dev-user-id':account}}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function submit(){if(category.id==='personal_assistance')return setError('Personal Assistance is temporarily unavailable pending enhanced screening.');if(!account)return setError('Choose a demo customer first.');if(!date||!address.trim())return setError('Provide an address and schedule.');const missing=category.fields.filter(f=>!form[f.key]?.trim());if(missing.length)return setError('Complete all service details.');const start=new Date(date);if(start<=new Date())return setError('Select a future date and time.');setBusy(true);setError('');try{const outcome=await request<{message?:string}>('/bookings',{method:'POST',headers:{'Content-Type':'application/json','x-dev-user-id':account},body:JSON.stringify({category:category.id,startsAt:start.toISOString(),endsAt:new Date(start.getTime()+2*3600000).toISOString(),address,intake:form})});setError(outcome.message||'');setScreen('history');const rows=await request<Booking[]>('/dev/bookings',{headers:{'x-dev-user-id':account}});setBookings(rows)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <div className="app"><header className="top"><BrandAsset/><span className="demo">DEVELOPMENT MVP</span></header><main className="content">
{!apiReady&&<div className="warning"><AlertCircle size={18}/><span>Backend connection required. This is a real API client, not a simulated booking screen.</span></div>}
{screen==='home'&&<><div className="eyebrow"><MapPin size={14}/> Home services, made easy</div><h1>What can we help you with today?</h1><p className="sub">Find qualified professionals for your home.</p><div className="search"><Search size={19}/><input aria-label="Search services" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search for a service"/></div><h2>Explore services</h2><div className="categories">{catalog.filter(x=>(x.name+' '+x.description).toLowerCase().includes(search.toLowerCase())).map(x=><button className="category" key={x.id} onClick={()=>choose(x.id)}><CategoryAsset category={x.id} fallback={x.icon}/><strong>{x.name}</strong><small>{x.description}</small><small>Test estimate from {php(demoPricing[x.id].starting)}</small><ArrowRight size={16} className="arrow"/></button>)}</div><div className="trust"><ShieldCheck size={21}/><span>Providers must be approved for each service category before receiving jobs.</span></div></>}
{screen==='book'&&<><button className="back" onClick={()=>setScreen('home')}><ArrowLeft size={18}/> All services</button><div className="service-head"><CategoryAsset category={category.id} fallback={category.icon}/><div><h1>{category.name}</h1><p className="sub">{category.description}</p><p className="note">Demo estimate: {php(demoPricing[category.id].typicalMin)}–{php(demoPricing[category.id].typicalMax)}. Provider quote may differ; materials and travel may be extra. No charge on booking.</p></div></div><section className="panel"><h2>Tell us about the job</h2><p className="sub">Provide enough information for an accurate quote. Full details are shared with the assigned provider after acceptance.</p>{category.fields.map(f=><label key={f.key}>{f.label}<input value={form[f.key]||''} placeholder={f.placeholder} onChange={e=>setForm(v=>({...v,[f.key]:e.target.value}))}/></label>)}<label>When do you need help?<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Service address<input value={address} placeholder="Street, barangay, city" onChange={e=>setAddress(e.target.value)}/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={!apiReady||busy} onClick={submit}>{busy?'Submitting…':'Request a professional'} <ArrowRight size={19}/></button><p className="note">Development mode only. No payment is collected. Eligible providers may receive offers when a booking is submitted.</p></section></>}
{screen==='history'&&<><h1>Your bookings</h1>{error&&<p role="status" className="warning">{error}</p>}<p className="sub">Requests saved in the development database.</p>{bookings.length?bookings.map(b=><article className="booking" key={b.id}><div className="row"><strong>{catalog.find(x=>x.id===b.category_code)?.name}</strong><span className="status">{b.status}</span></div><p><CalendarDays size={15}/>{new Date(b.starts_at).toLocaleString()}</p><p><MapPin size={15}/>{b.address_text}</p><small>Booking {b.id.slice(0,8)}</small><button className="secondary-action" onClick={()=>viewBooking(b.id)}>View activity</button>{['confirmed','in_progress','completed'].includes(b.status)&&<button className="secondary-action" disabled={busy} onClick={()=>disputeBooking(b.id)}>Raise dispute</button>}{['requested','matching','confirmed'].includes(b.status)&&<button className="secondary-action" disabled={busy} onClick={()=>cancelBooking(b.id)}>Cancel booking</button>}{b.status==='completed'&&<div className="rating"><strong>Demo rating (saved on this device)</strong><div className="offer-actions">{[1,2,3,4,5].map(n=><button type="button" className="secondary-action" key={n} aria-label={'Rate '+n+' stars'} aria-pressed={ratings[b.id]===n} onClick={()=>setRatings(old=>({...old,[b.id]:n}))}>{n} ★</button>)}</div>{ratings[b.id]&&<small>Your rating: {ratings[b.id]} of 5. Not published.</small>}</div>}{selected===b.id&&<section className="activity"><h3>Booking activity</h3>{detailBusy?<p>Loading activity…</p>:events.length?events.map((e,i)=><p key={i}><strong>{e.event_type.replaceAll('_',' ')}</strong> · {new Date(e.created_at).toLocaleString()}</p>):<p>No events recorded.</p>}</section>}</article>):<div className="empty"><CalendarDays size={32}/><h2>No bookings yet</h2><p>Find a service and create your first request.</p><button className="primary" onClick={()=>setScreen('home')}>Explore services</button></div>}</>}
{screen==='account'&&<><h1>Demo account</h1><p className="sub">Select one of 30 fictional customers for development testing.</p><section className="panel"><label>Active customer<select value={account} onChange={e=>setAccount(e.target.value)}>{accounts.map(a=><option value={a.id} key={a.id}>{a.display_name}</option>)}</select></label><button className="secondary-action" onClick={()=>{if(window.confirm('Clear local demo preferences and ratings?')){localStorage.removeItem('homiq:ratings');localStorage.removeItem('homiq:customer');setRatings({});setAccount(accounts[0]?.id||'')}}}>Reset local demo preferences</button><p className="note">Development identity selection is not authentication. Production deployment is blocked until secure sign-in and authorization are implemented.</p></section><div className="trust"><BriefcaseBusiness size={21}/><span>Provider and administrator development workspaces are available from the role selector above.</span></div></>}
</main><nav className="bottom" aria-label="Main navigation"><button className={screen==='home'?'active':''} onClick={()=>setScreen('home')}><Home size={22}/>Home</button><button className={screen==='history'?'active':''} onClick={()=>setScreen('history')}><CalendarDays size={22}/>Bookings</button><button className={screen==='account'?'active':''} onClick={()=>setScreen('account')}><UserRound size={22}/>Account</button></nav></div>
}
