import type {Express} from 'express';
import type {Pool,PoolClient} from 'pg';
import {z} from 'zod';
const input=z.object({amountCents:z.number().int().min(100).max(10000000),method:z.enum(['gcash','maya','bank']),destinationLabel:z.string().trim().min(2).max(120)});
const enabled=()=>process.env.NODE_ENV!=='production'&&process.env.ALLOW_INSECURE_DEV_AUTH==='true'&&process.env.ENABLE_DEMO_ROUTES==='true';
async function transaction<T>(pool:Pool,run:(c:PoolClient)=>Promise<T>){const c=await pool.connect();try{await c.query('BEGIN');const value=await run(c);await c.query('COMMIT');return value}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
class Rejected extends Error{constructor(public status:number,message:string){super(message)}}
const error=(res:any,e:unknown)=>e instanceof Rejected?res.status(e.status).json({error:e.message}):(console.error('Demo cashout error',e),res.status(500).json({error:'Cash-out simulation unavailable'}));
export function cashoutRoutes(app:Express,pool:Pool){
 const guard=(req:any,res:any,next:any)=>{if(!enabled())return res.status(404).json({error:'Not available'});next()};
 const provider=async(c:PoolClient,id:string)=>{const p=await c.query('SELECT 1 FROM providers WHERE user_id=$1 AND active=true',[id]);if(!p.rowCount)throw new Rejected(403,'Provider account required')};
 app.get('/api/provider/cashouts',guard,async(req,res)=>{const id=req.header('x-dev-user-id');if(!id)return res.sendStatus(401);try{const q=await pool.query('SELECT id,amount_cents,method,destination_label,status,created_at,decided_at,decision_note FROM demo_cashout_requests WHERE provider_user_id=$1 ORDER BY created_at DESC LIMIT 100',[id]);res.json(q.rows)}catch(e){error(res,e)}});
 app.post('/api/provider/cashouts',guard,async(req,res)=>{const id=req.header('x-dev-user-id');if(!id)return res.sendStatus(401);const parsed=input.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid cash-out request'});try{const result=await transaction(pool,async c=>{await provider(c,id);const w=await c.query('SELECT balance_cents,reserved_cents FROM demo_wallets WHERE user_id=$1 FOR UPDATE',[id]);if(!w.rowCount||Number(w.rows[0].balance_cents)-Number(w.rows[0].reserved_cents)<parsed.data.amountCents)throw new Rejected(409,'Insufficient available demo earnings');const q=await c.query('INSERT INTO demo_cashout_requests(provider_user_id,amount_cents,method,destination_label) VALUES($1,$2,$3,$4) RETURNING id,status,amount_cents,method,destination_label',[id,parsed.data.amountCents,parsed.data.method,parsed.data.destinationLabel]);await c.query('UPDATE demo_wallets SET reserved_cents=reserved_cents+$2,updated_at=now() WHERE user_id=$1',[id,parsed.data.amountCents]);await c.query("INSERT INTO demo_wallet_ledger(user_id,entry_type,amount_cents,idempotency_key) VALUES($1,'cashout_reserve',$2,$3)",[id,parsed.data.amountCents,'cashout:reserve:'+q.rows[0].id]);return q.rows[0]});res.status(201).json(result)}catch(e){error(res,e)}});
 const admin=(req:any,res:any,next:any)=>{if(!enabled())return res.sendStatus(404);if(!process.env.DEV_ADMIN_KEY||req.header('x-dev-admin-key')!==process.env.DEV_ADMIN_KEY)return res.sendStatus(403);next()};
 app.get('/api/dev/admin/cashouts',admin,async(_req,res)=>{try{const q=await pool.query("SELECT c.id,c.provider_user_id,u.display_name,c.amount_cents,c.method,c.destination_label,c.status,c.created_at,c.decision_note FROM demo_cashout_requests c JOIN users u ON u.id=c.provider_user_id ORDER BY CASE WHEN c.status='pending' THEN 0 ELSE 1 END,c.created_at DESC LIMIT 150");res.json(q.rows)}catch(e){error(res,e)}});
 app.post('/api/dev/admin/cashouts/:id/decision',admin,async(req,res)=>{const decision=z.object({decision:z.enum(['approve','reject']),note:z.string().trim().max(500).optional()}).safeParse(req.body);if(!decision.success)return res.status(400).json({error:'Invalid decision'});try{const result=await transaction(pool,async c=>{const q=await c.query('SELECT id,provider_user_id,amount_cents,status FROM demo_cashout_requests WHERE id=$1 FOR UPDATE',[req.params.id]);if(!q.rowCount)throw new Rejected(404,'Request not found');const item=q.rows[0];if(item.status!=='pending')throw new Rejected(409,'Request already decided');const amount=Number(item.amount_cents);const w=await c.query('SELECT balance_cents,reserved_cents FROM demo_wallets WHERE user_id=$1 FOR UPDATE',[item.provider_user_id]);if(!w.rowCount||Number(w.rows[0].reserved_cents)<amount)throw new Rejected(409,'Reserved demo earnings inconsistent');if(decision.data.decision==='approve'){const debit=await c.query('UPDATE demo_wallets SET balance_cents=balance_cents-$2,reserved_cents=reserved_cents-$2,updated_at=now() WHERE user_id=$1 AND balance_cents>=$2 AND reserved_cents>=$2 RETURNING user_id',[item.provider_user_id,amount]);if(!debit.rowCount)throw new Rejected(409,'Demo earnings insufficient')}else await c.query('UPDATE demo_wallets SET reserved_cents=reserved_cents-$2,updated_at=now() WHERE user_id=$1',[item.provider_user_id,amount]);const status=decision.data.decision==='approve'?'approved':'rejected';await c.query('UPDATE demo_cashout_requests SET status=$2,decided_at=now(),decision_note=$3 WHERE id=$1',[item.id,status,decision.data.note||null]);await c.query('INSERT INTO demo_wallet_ledger(user_id,entry_type,amount_cents,idempotency_key) VALUES($1,$2,$3,$4)',[item.provider_user_id,status==='approved'?'cashout_approve':'cashout_release',status==='approved'?-amount:amount,'cashout:'+status+':'+item.id]);return {id:item.id,status,amountCents:amount,fictional:true}});res.json(result)}catch(e){error(res,e)}});
}
