import type {Express} from 'express';
import type {Pool,PoolClient} from 'pg';
import {z} from 'zod';
class FlowError extends Error{constructor(public status:number,message:string){super(message)}}
const fail=(message:string,status=409):never=>{throw new FlowError(status,message)};
async function tx<T>(pool:Pool,fn:(c:PoolClient)=>Promise<T>){const c=await pool.connect();try{await c.query('BEGIN');const result=await fn(c);await c.query('COMMIT');return result}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
export function walletRoutes(app:Express,pool:Pool){
 const actor=(req:{header:(name:string)=>string|undefined})=>{const id=req.header('x-dev-user-id');return id&&/^[0-9a-f-]{36}$/i.test(id)?id:null};
 const handle=(res:any,e:unknown)=>{if(e instanceof FlowError)return res.status(e.status).json({error:e.message});console.error('Wallet flow failed',e);return res.status(500).json({error:'Wallet operation unavailable'})};
 app.get('/api/demo/wallet/ledger',async(req,res)=>{const id=actor(req);if(!id)return res.sendStatus(401);try{const q=await pool.query('SELECT booking_id,entry_type,amount_cents,created_at FROM demo_wallet_ledger WHERE user_id=$1 ORDER BY id DESC LIMIT 100',[id]);res.json(q.rows)}catch(e){handle(res,e)}});
 app.get('/api/bookings/:id/quotes',async(req,res)=>{const id=actor(req);if(!id)return res.sendStatus(401);try{const q=await pool.query(`SELECT q.id,q.amount_cents,q.status,q.created_at FROM quotes q JOIN bookings b ON b.id=q.booking_id LEFT JOIN assignments a ON a.booking_id=b.id LEFT JOIN providers p ON p.id=a.provider_id WHERE q.booking_id=$1 AND (b.customer_id=$2 OR p.user_id=$2) ORDER BY q.created_at DESC`,[req.params.id,id]);res.json(q.rows)}catch(e){handle(res,e)}});
 app.post('/api/bookings/:id/quotes',async(req,res)=>{const id=actor(req);if(!id)return res.sendStatus(401);const parsed=z.object({amountCents:z.number().int().min(100).max(10000000)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid quotation amount'});try{const result=await tx(pool,async c=>{const b=await c.query(`SELECT b.status,b.customer_id,a.provider_id,p.user_id AS provider_user_id FROM bookings b JOIN assignments a ON a.booking_id=b.id JOIN providers p ON p.id=a.provider_id WHERE b.id=$1 FOR UPDATE OF b`,[req.params.id]);if(!b.rowCount||b.rows[0].provider_user_id!==id)fail('Only assigned provider may quote',403);if(b.rows[0].status!=='confirmed')fail('Booking not awaiting quotation');const prior=await c.query("SELECT 1 FROM quotes WHERE booking_id=$1 AND status IN ('proposed','approved')",[req.params.id]);if(prior.rowCount)fail('Existing quote requires customer decision');const q=await c.query("INSERT INTO quotes(booking_id,provider_id,amount_cents) VALUES($1,$2,$3) RETURNING id,status,amount_cents",[req.params.id,b.rows[0].provider_id,parsed.data.amountCents]);await c.query("INSERT INTO booking_events(booking_id,actor_user_id,event_type,detail) VALUES($1,$2,'quote_proposed',$3)",[req.params.id,id,JSON.stringify({quoteId:q.rows[0].id,amountCents:parsed.data.amountCents})]);return q.rows[0]});res.status(201).json(result)}catch(e){handle(res,e)}});
 app.post('/api/bookings/:id/quotes/:quoteId/decision',async(req,res)=>{const id=actor(req);if(!id)return res.sendStatus(401);const decision=z.enum(['approve','reject']).safeParse(req.body?.decision);if(!decision.success)return res.status(400).json({error:'Invalid decision'});try{const result=await tx(pool,async c=>{const b=await c.query('SELECT customer_id,status FROM bookings WHERE id=$1 FOR UPDATE',[req.params.id]);if(!b.rowCount||b.rows[0].customer_id!==id)fail('Only customer may decide',403);if(b.rows[0].status!=='confirmed')fail('Booking not awaiting approval');const q=await c.query("SELECT id,amount_cents,status FROM quotes WHERE id=$1 AND booking_id=$2 FOR UPDATE",[req.params.quoteId,req.params.id]);if(!q.rowCount||q.rows[0].status!=='proposed')fail('Quotation no longer pending');const amount=Number(q.rows[0].amount_cents);if(decision.data==='approve'){const wallet=await c.query('SELECT balance_cents,reserved_cents FROM demo_wallets WHERE user_id=$1 FOR UPDATE',[id]);if(!wallet.rowCount||Number(wallet.rows[0].balance_cents)-Number(wallet.rows[0].reserved_cents)<amount)fail('Insufficient available demo wallet credits');await c.query('UPDATE demo_wallets SET reserved_cents=reserved_cents+$2,updated_at=now() WHERE user_id=$1',[id,amount]);await c.query("INSERT INTO demo_wallet_holds(booking_id,customer_id,amount_cents,status) VALUES($1,$2,$3,'reserved')",[req.params.id,id,amount]);await c.query("INSERT INTO demo_wallet_ledger(user_id,booking_id,entry_type,amount_cents,idempotency_key) VALUES($1,$2,'reserve',$3,$4)",[id,req.params.id,amount,'reserve:'+req.params.id]);await c.query('UPDATE bookings SET agreed_price_cents=$2 WHERE id=$1',[req.params.id,amount])}await c.query('UPDATE quotes SET status=$2 WHERE id=$1',[req.params.quoteId,decision.data==='approve'?'approved':'rejected']);await c.query('INSERT INTO booking_events(booking_id,actor_user_id,event_type,detail) VALUES($1,$2,$3,$4)',[req.params.id,id,'quote_'+(decision.data==='approve'?'approved':'rejected'),JSON.stringify({quoteId:req.params.quoteId,amountCents:amount})]);return {decision:decision.data,amountCents:amount}});res.json(result)}catch(e){handle(res,e)}});
 app.post('/api/bookings/:id/confirm-delivery',async(req,res)=>{const id=actor(req);if(!id)return res.sendStatus(401);try{const result=await tx(pool,async c=>{const b=await c.query(`SELECT b.customer_id,b.status,a.provider_id,p.user_id AS provider_user_id FROM bookings b JOIN assignments a ON a.booking_id=b.id JOIN providers p ON p.id=a.provider_id WHERE b.id=$1 FOR UPDATE OF b`,[req.params.id]);if(!b.rowCount||b.rows[0].customer_id!==id)fail('Only booking customer may confirm',403);if(b.rows[0].status==='settled')return {status:'settled',alreadySettled:true};if(b.rows[0].status!=='completed')fail('Provider must complete job before delivery confirmation');const hold=await c.query("SELECT amount_cents,status FROM demo_wallet_holds WHERE booking_id=$1 FOR UPDATE",[req.params.id]);if(!hold.rowCount||hold.rows[0].status!=='reserved')fail('No active payment reservation');const amount=Number(hold.rows[0].amount_cents);await c.query('SELECT user_id FROM demo_wallets WHERE user_id IN ($1,$2) ORDER BY user_id FOR UPDATE',[id,b.rows[0].provider_user_id]);const debit=await c.query('UPDATE demo_wallets SET balance_cents=balance_cents-$2,reserved_cents=reserved_cents-$2,updated_at=now() WHERE user_id=$1 AND balance_cents>=$2 AND reserved_cents>=$2 RETURNING user_id',[id,amount]);if(!debit.rowCount)fail('Wallet reservation inconsistent');const credit=await c.query('UPDATE demo_wallets SET balance_cents=balance_cents+$2,updated_at=now() WHERE user_id=$1 RETURNING user_id',[b.rows[0].provider_user_id,amount]);if(!credit.rowCount)fail('Provider demo wallet not seeded');await c.query("UPDATE demo_wallet_holds SET status='captured',settled_at=now() WHERE booking_id=$1",[req.params.id]);await c.query("INSERT INTO demo_wallet_ledger(user_id,booking_id,entry_type,amount_cents,idempotency_key) VALUES($1,$2,'capture',$3,$4),($5,$2,'earning',$3,$6)",[id,req.params.id,-amount,'capture:'+req.params.id,b.rows[0].provider_user_id,'earning:'+req.params.id]);await c.query("UPDATE bookings SET status='settled' WHERE id=$1",[req.params.id]);await c.query("INSERT INTO booking_events(booking_id,actor_user_id,event_type,detail) VALUES($1,$2,'delivery_confirmed',$3)",[req.params.id,id,JSON.stringify({amountCents:amount,fictional:true})]);return {status:'settled',amountCents:amount,fictional:true}});res.json(result)}catch(e){handle(res,e)}});
}
